#!/usr/bin/env bash

## Test site installation
##
## Usage: fin test

# Abort if anything fails
set -e

# Debug mode switch
if [[ "${DEBUG}" != "" ]]; then
    set -x
fi

echo "Testing home page..."
curl -sL -I http://${VIRTUAL_HOST} | grep "HTTP/1.1 200 OK"
curl -sL http://${VIRTUAL_HOST} | grep "Home Page"
echo "Testing login page..."
curl -sL -I http://${VIRTUAL_HOST}/customer/account/login | grep "HTTP/1.1 200 OK"
